name: Docker Image CI

on:
  push:
    branches: [ 'main' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Obtain repository and tag names
        shell: bash
        run: |
             if [ -z "${{ secrets.DOCKER_HUB_REPO }}" ]; then
                 echo "repo=${{ secrets.DOCKER_HUB_USERNAME }}" >> $GITHUB_OUTPUT
             else
                 echo "repo=${{ secrets.DOCKER_HUB_REPO }}" >> $GITHUB_OUTPUT
             fi
             echo "tag=$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')" >> $GITHUB_OUTPUT
        id: extract_tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.extract_tag.outputs.repo }}/ubuntu-vnc-desktop-spimbot:${{ steps.extract_tag.outputs.tag }}
          cache-from: type=gha,ref=${{ steps.extract_tag.outputs.repo }}/ubuntu-vnc-desktop-spimbot:buildcache
          cache-to: type=registry,ref=${{ steps.extract_tag.outputs.repo }}/ubuntu-vnc-desktop-spimbot:buildcache,mode=max
      # - name: Move cache
      #   # This ugly bit is necessary if you don't want your cache to grow forever
      #   # until it hits GitHub's limit of 5GB.
      #   # Temp fix
      #   # https://github.com/docker/build-push-action/issues/252
      #   # https://github.com/moby/buildkit/issues/1896
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete existing tag (latest)
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest'
            })
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: 'spimbot_docker_release.zip'
          path: 'spimbot_release/'
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: spimbot_docker_release.zip
          allowUpdates: true
          tag: latest
          commit: main
          makeLatest: true
      - name: Delete zip file
        run: rm spimbot_docker_release.zip
          
          
# Reference: https://docs.docker.com/ci-cd/github-actions/
